export const designers = [
  { id: 1,  name: "김도연 22",      photo: "photo-15.webp", track: "UX / MO"  },
  { id: 2,  name: "김도연 23",      photo: "photo-4.webp",  track: "XR / UX"  },
  { id: 3,  name: "김수민",          photo: "photo-18.webp", track: "XR / UX"  },
  { id: 4,  name: "김지아",          photo: "photo-12.webp", track: "UX / MO"  },
  { id: 5,  name: "김지유",          photo: "photo-5.webp",  track: "UX / UI"  },
  { id: 6,  name: "김채현",          photo: "photo-6.webp",  track: "XR / MO"  },
  { id: 7,  name: "김태린",          photo: "photo.webp",    track: "UX / UI"  },
  { id: 8,  name: "박서영",          photo: "photo-3.webp",  track: "XR / MO"  },
  { id: 9,  name: "박서하",          photo: "photo-11.webp", track: "UX / MO"  },
  { id: 10, name: "박소정",          photo: "photo-3.webp",  track: "XR / MO"  },
  { id: 11, name: "박채원",          photo: "photo-16.webp", track: "UX"       },
  { id: 12, name: "서유정",          photo: "photo-2.webp",  track: "XR / UX"  },
  { id: 13, name: "서한이",          photo: "photo-17.webp", track: "UX / UI"  },
  { id: 14, name: "신민지",          photo: "photo-10.webp", track: "MO"       },
  { id: 15, name: "오연서",          photo: "photo-3.webp",  track: "UI / MO"  },
  { id: 16, name: "윤내경",          photo: "photo-19.webp", track: "UX / MO"  },
  { id: 17, name: "응웬짠휘엔아잉",  photo: "photo-3.webp",  track: "UX / MO"  },
  { id: 18, name: "이유진",          photo: "photo-3.webp",  track: "XR / MO"  },
  { id: 19, name: "전지민",          photo: "photo-7.webp",  track: "XR / UX"  },
  { id: 20, name: "정가람",          photo: "photo-3.webp",  track: "MO"       },
  { id: 21, name: "정윤서",          photo: "photo-3.webp",  track: "XR / MO"  },
  { id: 22, name: "정지연",          photo: "photo-14.webp", track: "XR"       },
  { id: 23, name: "조연진",          photo: "photo-9.webp",  track: "XR / MO"  },
  { id: 24, name: "진민서",          photo: "photo-1.webp",  track: "UX / UI"  },
  { id: 25, name: "천세진",          photo: "photo-13.webp", track: "UX / MO"  },
  { id: 26, name: "현명화",          photo: "photo-8.webp",  track: "UX / MO"  },
  { id: 27, name: "황태희",          photo: "photo-20.webp", track: "XR / MO"  },
  { id: 28, name: "황희주",          photo: "photo-3.webp",  track: "MO"       },
];
