export type Work = { id: number; name: string; category: string };

export const works: Work[] = [
  { id: 1,  name: "Coco", category: "UI" },
  { id: 2,  name: "",     category: "UI" },
  { id: 3,  name: "",     category: "UI" },
  { id: 4,  name: "",     category: "XR" },
  { id: 5,  name: "",     category: "XR" },
  { id: 6,  name: "",     category: "XR" },
  { id: 7,  name: "",     category: "XR" },
  { id: 8,  name: "",     category: "XR" },
  { id: 9,  name: "",     category: "XR" },
  { id: 10, name: "",     category: "XR" },
  { id: 11, name: "",     category: "XR" },
  { id: 12, name: "",     category: "XR" },
  { id: 13, name: "",     category: "XR" },
  { id: 14, name: "",     category: "UX" },
  { id: 15, name: "",     category: "UX" },
  { id: 16, name: "",     category: "MOTION" },
  { id: 17, name: "",     category: "MOTION" },
  { id: 18, name: "",     category: "MOTION" },
  { id: 19, name: "",     category: "MOTION" },
  { id: 20, name: "",     category: "MOTION" },
  { id: 21, name: "",     category: "MOTION" },
  { id: 22, name: "",     category: "MOTION" },
  { id: 23, name: "",     category: "MOTION" },
];
